# Generated by Django 5.2 on 2026-06-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_invoicealertsubscription_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicealertsubscription',
            name='email_enabled',
            field=models.BooleanField(default=False, verbose_name='E-Mail-Benachrichtigung'),
        ),
        migrations.AddField(
            model_name='stockalertsubscription',
            name='email_enabled',
            field=models.BooleanField(default=False, verbose_name='E-Mail-Benachrichtigung'),
        ),
    ]
