# Generated by Django 5.2 on 2026-06-25 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import emails.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.CharField(max_length=255)),
                ('recipient', models.CharField(max_length=255)),
                ('cc', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('sent', 'Versendet'), ('failed', 'Fehlgeschlagen')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'E-Mail',
                'verbose_name_plural': 'E-Mails',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=emails.models.email_attachment_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='emails.emaillog')),
            ],
            options={
                'verbose_name': 'E-Mail-Anhang',
                'verbose_name_plural': 'E-Mail-Anhänge',
            },
        ),
    ]
