# Generated by Django 5.2 on 2026-03-25 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('pos_import', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='dot_bezeichnung', max_length=255)),
            ],
            options={
                'db_table': 'dokumenttypen',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='lieferant_name', max_length=255)),
                ('partner_type', models.CharField(choices=[('supplier', 'Lieferant'), ('consumer', 'Verbraucher')], default='supplier', max_length=20)),
            ],
            options={
                'db_table': 'partner',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='sts_bezeichnung', max_length=255)),
                ('percent', models.DecimalField(db_column='sts_prozent', decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'steuersaetze',
                'ordering': ['percent'],
            },
        ),
        migrations.CreateModel(
            name='EkModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('+', '+'), ('-', '-'), ('*', '*'), ('/', '/')], db_column='emo_operator', max_length=1)),
                ('modifier', models.DecimalField(db_column='emo_modifikator', decimal_places=4, max_digits=10)),
                ('article', models.ForeignKey(db_column='emo_artikel_id', on_delete=django.db.models.deletion.CASCADE, related_name='ek_modifiers', to='pos_import.article')),
                ('period', models.ForeignKey(db_column='emo_periode_id', on_delete=django.db.models.deletion.CASCADE, to='core.period')),
            ],
            options={
                'db_table': 'ek_modifikatoren',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_column='datum')),
                ('movement_type', models.CharField(choices=[('delivery', 'Lieferung'), ('consumption', 'Verbrauch')], default='delivery', max_length=20)),
                ('comment', models.TextField(blank=True, db_column='lie_kommentar', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(db_column='partner_id', on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='deliveries.partner')),
                ('period', models.ForeignKey(blank=True, db_column='lie_periode_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='core.period')),
            ],
            options={
                'db_table': 'lagerbewegungen',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='dok_bezeichnung', max_length=255)),
                ('ocr_text', models.TextField(blank=True, db_column='dok_ocr', null=True)),
                ('data', models.BinaryField(db_column='dok_data')),
                ('date', models.DateTimeField(db_column='dok_datum')),
                ('doc_type', models.ForeignKey(db_column='dok_dotid', on_delete=django.db.models.deletion.PROTECT, to='deliveries.documenttype')),
                ('stock_movement', models.ForeignKey(blank=True, db_column='dok_lagerbewegung_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='deliveries.stockmovement')),
            ],
            options={
                'db_table': 'dokumente',
            },
        ),
        migrations.CreateModel(
            name='StockMovementDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(db_column='anzahl', decimal_places=3, max_digits=10)),
                ('unit_price', models.DecimalField(db_column='einkaufspreis', decimal_places=4, max_digits=10)),
                ('article', models.ForeignKey(db_column='artikel_id', on_delete=django.db.models.deletion.PROTECT, to='pos_import.article')),
                ('stock_movement', models.ForeignKey(db_column='lagerbewegung_id', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='deliveries.stockmovement')),
                ('tax_rate', models.ForeignKey(blank=True, db_column='lde_stsid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliveries.taxrate')),
            ],
            options={
                'db_table': 'lagerbewegungen_details',
            },
        ),
    ]
