# Generated by Django 5.0.6 on 2026-03-23 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='lei_bezeichnung', max_length=255)),
                ('quantity', models.DecimalField(db_column='lei_menge', decimal_places=3, max_digits=10)),
            ],
            options={
                'db_table': 'liefereinheiten',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='dot_bezeichnung', max_length=255)),
            ],
            options={
                'db_table': 'dokumenttypen',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='lieferant_name', max_length=255)),
                ('is_consumer', models.BooleanField(db_column='lft_ist_verbraucher', default=False)),
            ],
            options={
                'db_table': 'lieferanten',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='sts_bezeichnung', max_length=255)),
                ('percent', models.DecimalField(db_column='sts_prozent', decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'steuersaetze',
                'ordering': ['percent'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_column='datum')),
                ('is_consumption', models.BooleanField(db_column='lie_ist_verbrauch', default=False)),
                ('comment', models.TextField(blank=True, db_column='lie_kommentar', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.ForeignKey(blank=True, db_column='lie_periode_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='core.period')),
                ('supplier', models.ForeignKey(db_column='lieferant_id', on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='deliveries.supplier')),
            ],
            options={
                'db_table': 'lieferungen',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='dok_bezeichnung', max_length=255)),
                ('ocr_text', models.TextField(blank=True, db_column='dok_ocr', null=True)),
                ('data', models.BinaryField(db_column='dok_data')),
                ('date', models.DateTimeField(db_column='dok_datum')),
                ('delivery', models.ForeignKey(blank=True, db_column='dok_lieferung_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='deliveries.delivery')),
                ('doc_type', models.ForeignKey(db_column='dok_dotid', on_delete=django.db.models.deletion.PROTECT, to='deliveries.documenttype')),
            ],
            options={
                'db_table': 'dokumente',
            },
        ),
        migrations.CreateModel(
            name='DeliveryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(db_column='anzahl', decimal_places=3, max_digits=10)),
                ('unit_price', models.DecimalField(db_column='einkaufspreis', decimal_places=4, max_digits=10)),
                ('article', models.ForeignKey(db_column='artikel_id', on_delete=django.db.models.deletion.PROTECT, to='articles.article')),
                ('delivery', models.ForeignKey(db_column='lieferung_id', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='deliveries.delivery')),
                ('delivery_unit', models.ForeignKey(blank=True, db_column='lde_lei_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliveries.deliveryunit')),
                ('tax_rate', models.ForeignKey(blank=True, db_column='lde_stsid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliveries.taxrate')),
            ],
            options={
                'db_table': 'lieferungen_details',
            },
        ),
    ]
