# Generated by Django 5.2 on 2026-04-01 09:04

import deliveries.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_stockmovementdetail_tax_rate_not_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='doc_type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='stock_movement',
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=deliveries.models.attachment_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('source_filename', models.CharField(blank=True, default='', help_text='Original PDF filename when this image was extracted from a PDF.', max_length=255)),
                ('page_number', models.PositiveIntegerField(blank=True, help_text='Page number (1-based) if extracted from a PDF.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock_movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='deliveries.stockmovement')),
            ],
            options={
                'ordering': ['source_filename', 'page_number', 'created_at'],
            },
        ),
        migrations.DeleteModel(
            name='DocumentType',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
