# Generated by Django 5.2 on 2026-04-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0005_remove_document_doc_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='llm_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
