# Generated by Django 5.2 on 2026-04-02 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0006_add_partner_llm_instructions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='llm_instructions',
        ),
        migrations.CreateModel(
            name='PartnerAiInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('instructions', models.TextField(blank=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_instructions', to='deliveries.partner')),
            ],
            options={
                'ordering': ['provider'],
                'unique_together': {('partner', 'provider')},
            },
        ),
    ]
