# Generated by Django 5.2 on 2026-04-02 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0007_remove_partner_llm_instructions_partneraiinstruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='stock_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='deliveries.stockmovement'),
        ),
    ]
