# Generated by Django 5.2 on 2026-04-04 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0008_attachment_nullable_movement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EkModifier',
        ),
    ]
