# Generated by Django 5.2 on 2026-04-11 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0009_remove_ekmodifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='partner_type',
        ),
    ]
