# Generated by Django 5.2 on 2026-07-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0010_remove_partner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='flag',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
