# Generated by Django 5.2 on 2026-07-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0011_stockmovement_flag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovementdetail',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='stockmovementdetail',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
