# Generated by Django 5.2 on 2026-06-18 08:27

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0010_remove_partner_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wz_source_id', models.IntegerField(blank=True, help_text='adresse_id from adressen_basis in Wiffzack; null for locally-created addresses.', null=True, unique=True)),
                ('anrede', models.CharField(blank=True, max_length=255, null=True)),
                ('vorname', models.CharField(blank=True, max_length=50, null=True)),
                ('nachname', models.CharField(blank=True, max_length=50, null=True)),
                ('firma', models.TextField(blank=True, null=True)),
                ('abteilung', models.TextField(blank=True, null=True)),
                ('strasse', models.CharField(blank=True, max_length=100, null=True)),
                ('plz', models.CharField(blank=True, max_length=10, null=True)),
                ('ort', models.CharField(blank=True, max_length=50, null=True)),
                ('telefon', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('uid', models.TextField(blank=True, null=True, verbose_name='UID-Nummer')),
                ('anmerkung', models.TextField(blank=True, null=True)),
                ('ist_stammgast', models.BooleanField(default=False)),
                ('ist_lieferant', models.BooleanField(default=False)),
                ('ist_gast', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adressen',
                'ordering': ['nachname', 'vorname', 'firma'],
            },
        ),
        migrations.CreateModel(
            name='BillingArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_articles', to='deliveries.taxrate')),
            ],
            options={
                'verbose_name': 'Faktura-Artikel',
                'verbose_name_plural': 'Faktura-Artikel',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('issued', 'Ausgestellt'), ('paid', 'Bezahlt'), ('cancelled', 'Storniert')], default='draft', max_length=20)),
                ('recipient_text', models.TextField(blank=True)),
                ('document_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.address')),
            ],
            options={
                'verbose_name': 'Rechnung',
                'verbose_name_plural': 'Rechnungen',
                'ordering': ['-document_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=500)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('billing_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='billing.billingarticle')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.invoice')),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='deliveries.taxrate')),
            ],
            options={
                'verbose_name': 'Rechnungszeile',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('offer', 'Angebot'), ('invoice', 'Rechnung'), ('reminder', 'Mahnung')], max_length=20)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('last_value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Nummernfolge',
                'unique_together': {('doc_type', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('sent', 'Versendet'), ('accepted', 'Angenommen'), ('rejected', 'Abgelehnt'), ('converted', 'In Rechnung gestellt')], default='draft', max_length=20)),
                ('recipient_text', models.TextField(blank=True)),
                ('document_date', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='billing.address')),
            ],
            options={
                'verbose_name': 'Angebot',
                'verbose_name_plural': 'Angebote',
                'ordering': ['-document_date', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='source_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.offer'),
        ),
        migrations.CreateModel(
            name='OfferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=500)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('billing_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_lines', to='billing.billingarticle')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.offer')),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offer_lines', to='deliveries.taxrate')),
            ],
            options={
                'verbose_name': 'Angebotszeile',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, help_text='Mahnstufe (1–3)')),
                ('number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('issued', 'Ausgestellt'), ('paid', 'Bezahlt')], default='draft', max_length=20)),
                ('reminder_date', models.DateField()),
                ('due_date', models.DateField()),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reminders', to='billing.invoice')),
            ],
            options={
                'verbose_name': 'Mahnung',
                'verbose_name_plural': 'Mahnungen',
                'ordering': ['-reminder_date', '-pk'],
            },
        ),
    ]
