# Generated by Django 5.2 on 2026-06-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Artikel-Nummernfolge',
            },
        ),
    ]
