# Generated by Django 5.2 on 2026-06-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_article_number_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('draft', 'Entwurf'), ('issued', 'Ausgestellt'), ('sent', 'Versendet'), ('accepted', 'Angenommen'), ('rejected', 'Abgelehnt'), ('converted', 'In Rechnung gestellt')], default='draft', max_length=20),
        ),
    ]
