# Generated by Django 5.2 on 2026-06-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_offer_status_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Entwurf'), ('issued', 'Ausgestellt'), ('sent', 'Versendet'), ('paid', 'Bezahlt'), ('cancelled', 'Storniert')], default='draft', max_length=20),
        ),
    ]
