# Generated by Django 5.2 on 2026-06-20 04:09

import django.db.models.deletion
from django.db import migrations, models


def delete_billing_documents(apps: object, schema_editor: object) -> None:
    """
    Purge all billing documents before moving Address to core.
    Required because existing Offer/Invoice rows reference billing.Address IDs
    that don't exist in the new core.Address table.
    """
    Reminder = apps.get_model('billing', 'Reminder')  # type: ignore[attr-defined]
    InvoiceLine = apps.get_model('billing', 'InvoiceLine')  # type: ignore[attr-defined]
    Invoice = apps.get_model('billing', 'Invoice')  # type: ignore[attr-defined]
    OfferLine = apps.get_model('billing', 'OfferLine')  # type: ignore[attr-defined]
    Offer = apps.get_model('billing', 'Offer')  # type: ignore[attr-defined]
    Address = apps.get_model('billing', 'Address')  # type: ignore[attr-defined]
    Reminder.objects.all().delete()
    InvoiceLine.objects.all().delete()
    Invoice.objects.all().delete()
    OfferLine.objects.all().delete()
    Offer.objects.all().delete()
    Address.objects.all().delete()


class Migration(migrations.Migration):

    atomic = False  # RunPython + DDL cannot share a transaction in PostgreSQL

    dependencies = [
        ('billing', '0005_alter_invoice_due_date'),
        ('core', '0007_address'),
    ]

    operations = [
        migrations.RunPython(delete_billing_documents, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='offer',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='core.address'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.address'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
