# Generated by Django 5.2 on 2026-06-21 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_offer_address_alter_invoice_address_and_more'),
        ('deliveries', '0010_remove_partner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reverses',
            field=models.ForeignKey(blank=True, help_text='Bei Stornorechnungen: die stornierte Originalrechnung.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_by', to='billing.invoice'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='billing_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_lines', to='billing.billingarticle'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='tax_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lines', to='deliveries.taxrate'),
        ),
        migrations.AlterField(
            model_name='offerline',
            name='billing_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_lines', to='billing.billingarticle'),
        ),
        migrations.AlterField(
            model_name='offerline',
            name='tax_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lines', to='deliveries.taxrate'),
        ),
    ]
