# Generated by Django 5.2 on 2026-07-24 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_add_invoice_reverses_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='document_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
