# Generated by Django 5.2 on 2026-07-24 08:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_invoice_service_date_alter_invoice_document_date'),
        ('deliveries', '0012_alter_stockmovementdetail_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rechnungsvorlage',
                'verbose_name_plural': 'Rechnungsvorlagen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceTemplateLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=500)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('billing_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_lines', to='billing.billingarticle')),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lines', to='deliveries.taxrate')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.invoicetemplate')),
            ],
            options={
                'verbose_name': 'Vorlagenzeile',
                'ordering': ['position'],
                'abstract': False,
            },
        ),
    ]
