# Generated by Django 5.2 on 2026-09-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_invoicetemplate_invoicetemplateline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinuousNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('offer', 'Angebot'), ('invoice', 'Rechnung'), ('reminder', 'Mahnung')], max_length=20, unique=True)),
                ('last_value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Fortlaufende Nummernfolge',
                'verbose_name_plural': 'Fortlaufende Nummernfolgen',
            },
        ),
    ]
