# Generated by Django 5.2 on 2026-09-16 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_continuousnumbersequence'),
        ('core', '0008_customernumbersequence_customer_address_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.customer'),
        ),
        migrations.AddField(
            model_name='offer',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='core.customer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Entwurf'), ('issued', 'Ausgestellt'), ('sent', 'Versendet'), ('partially_paid', 'Teilweise bezahlt'), ('paid', 'Bezahlt'), ('cancelled', 'Storniert')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='Zahlungsdatum')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Betrag')),
                ('method', models.CharField(choices=[('transfer', 'Überweisung'), ('cash', 'Bar'), ('card', 'Karte'), ('credit', 'Guthaben'), ('other', 'Sonstiges')], default='transfer', max_length=20, verbose_name='Zahlungsart')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.invoice')),
            ],
            options={
                'verbose_name': 'Zahlung',
                'verbose_name_plural': 'Zahlungen',
                'ordering': ['payment_date', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CustomerLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('invoice', 'Rechnung'), ('reminder_fee', 'Mahngebühr'), ('payment', 'Zahlung'), ('adjustment', 'Korrektur')], max_length=20)),
                ('entry_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, help_text='Signed: negative = charge, positive = payment.', max_digits=18)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='core.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='billing.invoice')),
                ('reminder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='billing.reminder')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='billing.payment')),
            ],
            options={
                'verbose_name': 'Kontobewegung',
                'verbose_name_plural': 'Kontobewegungen',
                'ordering': ['entry_date', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='customerledgerentry',
            index=models.Index(fields=['customer', 'entry_date'], name='ledger_customer_date_idx'),
        ),
    ]
