# Generated by Django 5.2 on 2026-09-21 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import billing.models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_invoice_customer_offer_customer_alter_invoice_status_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('kind', models.CharField(db_index=True, max_length=32)),
                ('position', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('file', models.FileField(blank=True, null=True, upload_to=billing.models.document_attachment_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('delivery', models.CharField(choices=[('merge', 'An Dokument-PDF anhängen'), ('separate', 'Eigener Anhang')], default='merge', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dokument-Anhang',
                'verbose_name_plural': 'Dokument-Anhänge',
                'ordering': ['position', 'pk'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='doc_attachment_owner_idx')],
            },
        ),
    ]
