# Generated by Django 5.2 on 2026-09-26 11:15

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

# billing.services.payment_supplement.PAYMENTS_KIND, frozen here: a migration
# must not change meaning when the application code does.
PAYMENTS_KIND = 'payments'


def create_payment_supplements(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Give every invoice with payments or an issued reminder its Zahlungsübersicht.

    From now on services/payment_supplement.py creates it with the first payment
    or issued reminder; older invoices need it once, or they would go out
    without their payments and fees now that invoice.html no longer prints them.
    Mirrors payment_supplement.needs_payment_supplement().
    """
    ContentType = apps.get_model('contenttypes', 'ContentType')
    DocumentAttachment = apps.get_model('billing', 'DocumentAttachment')
    Payment = apps.get_model('billing', 'Payment')
    Reminder = apps.get_model('billing', 'Reminder')

    invoice_ids: set[int] = set(
        Payment.objects.filter(invoice__isnull=False).values_list('invoice_id', flat=True))
    invoice_ids |= set(
        Reminder.objects.exclude(status='draft').values_list('invoice_id', flat=True))
    if not invoice_ids:
        return
    content_type, _created = ContentType.objects.get_or_create(
        app_label='billing', model='invoice')
    existing: set[int] = set(
        DocumentAttachment.objects
        .filter(content_type=content_type, kind=PAYMENTS_KIND)
        .values_list('object_id', flat=True))
    DocumentAttachment.objects.bulk_create([
        DocumentAttachment(
            content_type=content_type,
            object_id=invoice_id,
            kind=PAYMENTS_KIND,
            position=0,
            delivery='merge',
        )
        for invoice_id in sorted(invoice_ids - existing)
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_documentattachment'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        # Reversing keeps the rows: code without the handler treats them as an
        # unknown kind, which is readable and simply never sent.
        migrations.RunPython(create_payment_supplements, migrations.RunPython.noop),
    ]
