# Generated by Django 5.2 on 2026-03-30 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('pos_import', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='period',
            field=models.ForeignKey(db_column='artikel_periode', on_delete=django.db.models.deletion.CASCADE, to='core.period'),
        ),
        migrations.AlterField(
            model_name='warehousearticle',
            name='period',
            field=models.ForeignKey(db_column='lager_artikel_periode', on_delete=django.db.models.deletion.CASCADE, to='core.period'),
        ),
    ]
