# Generated by Django 5.2 on 2026-04-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_import', '0002_alter_article_period_alter_warehousearticle_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(unique=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('sub_articles', models.TextField(blank=True)),
                ('periods', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Article Meta',
                'verbose_name_plural': 'Article Meta',
            },
        ),
    ]
