# Generated by Django 5.2 on 2026-04-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_import', '0004_articlemeta_period'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='articlemeta',
            name='package_size',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
