# Generated by Django 5.2 on 2026-04-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_workplace_to_location'),
        ('pos_import', '0005_add_package_size_to_articlemeta'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tischaktiv',
            index=models.Index(fields=['checkpoint_tag'], name='tische_aktiv_chkpt_tag_idx'),
        ),
    ]
