# Generated by Django 5.2 on 2026-05-06 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_import', '0006_add_checkpoint_tag_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehousearticle',
            options={'ordering': ['article__name']},
        ),
    ]
