# Generated by Django 5.2 on 2026-05-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_import', '0007_alter_warehousearticle_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemeta',
            name='minimum_inventory',
            field=models.IntegerField(default=0),
        ),
    ]
