# Generated by Django 5.0.6 on 2026-03-23 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(db_column='artikel_gruppe_id')),
                ('parent_source_id', models.IntegerField(blank=True, db_column='artikel_gruppe_parent_id', null=True)),
                ('name', models.CharField(db_column='artikel_gruppe_name', max_length=50)),
                ('standard_course', models.IntegerField(db_column='artikel_gruppe_standard_gangfolge')),
                ('bon_type', models.IntegerField(blank=True, db_column='artikel_gruppe_bontyp', null=True)),
                ('is_revenue', models.BooleanField(db_column='artikel_gruppe_istUmsatz')),
                ('show_on_receipt', models.BooleanField(db_column='artikel_gruppe_zeigeAufRechnung')),
                ('print_recipe', models.BooleanField(db_column='artikel_gruppe_druckeRezeptur')),
                ('no_cancellation', models.BooleanField(db_column='artikel_gruppe_keinStorno')),
                ('period', models.ForeignKey(db_column='artikel_gruppe_periode', on_delete=django.db.models.deletion.CASCADE, to='core.period')),
            ],
            options={
                'db_table': 'artikel_gruppen',
                'unique_together': {('source_id', 'period')},
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(db_column='artikel_id')),
                ('name', models.CharField(db_column='artikel_bezeichnung', max_length=50)),
                ('sales_price', models.DecimalField(blank=True, db_column='artikel_ep', decimal_places=2, max_digits=18, null=True)),
                ('sales_price_vat', models.IntegerField(blank=True, db_column='artikel_ep_mwst', null=True)),
                ('price_popup', models.BooleanField(db_column='artikel_preis_popup')),
                ('ep_price_popup', models.BooleanField(db_column='artikel_ep_preis_popup')),
                ('note', models.TextField(blank=True, db_column='artikel_bemerkung', null=True)),
                ('name_2', models.TextField(blank=True, db_column='artikel_bezeichnung_2', null=True)),
                ('rksv', models.BooleanField(db_column='artikel_rksv')),
                ('external_receipt', models.BooleanField(db_column='artikel_externer_beleg')),
                ('period', models.ForeignKey(blank=True, db_column='artikel_periode', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.period')),
                ('group', models.ForeignKey(blank=True, db_column='artikel_gruppe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.articlegroup')),
            ],
            options={
                'db_table': 'artikel_basis',
                'unique_together': {('source_id', 'period')},
            },
        ),
        migrations.CreateModel(
            name='EkModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('+', '+'), ('-', '-'), ('*', '*'), ('/', '/')], db_column='emo_operator', max_length=1)),
                ('modifier', models.DecimalField(db_column='emo_modifikator', decimal_places=4, max_digits=10)),
                ('article', models.ForeignKey(db_column='emo_artikel_id', on_delete=django.db.models.deletion.CASCADE, related_name='ek_modifiers', to='articles.article')),
                ('period', models.ForeignKey(db_column='emo_periode_id', on_delete=django.db.models.deletion.CASCADE, to='core.period')),
            ],
            options={
                'db_table': 'ek_modifikatoren',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(db_column='zutate_menge', decimal_places=4, max_digits=10)),
                ('is_fixed', models.BooleanField(db_column='zutate_istFixiert')),
                ('is_ingredient', models.BooleanField(db_column='zutate_istZutat')),
                ('is_recipe', models.BooleanField(db_column='zutate_istRezept')),
                ('always_show', models.BooleanField(db_column='zutate_immerAnzeigen')),
                ('is_mandatory', models.BooleanField(db_column='zutate_istZwangsAbfrage')),
                ('use_price', models.BooleanField(db_column='zutate_preisVerwenden')),
                ('ingredient_article', models.ForeignKey(db_column='zutate_artikel', on_delete=django.db.models.deletion.CASCADE, related_name='used_in_recipes', to='articles.article')),
                ('master_article', models.ForeignKey(db_column='zutate_master_artikel', on_delete=django.db.models.deletion.CASCADE, related_name='recipe_components', to='articles.article')),
                ('period', models.ForeignKey(db_column='zutate_periode', on_delete=django.db.models.deletion.CASCADE, to='core.period')),
            ],
            options={
                'db_table': 'artikel_zutaten',
            },
        ),
        migrations.CreateModel(
            name='WarehouseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(db_column='lager_einheit_id')),
                ('name', models.TextField(db_column='lager_einheit_name')),
                ('multiplier', models.DecimalField(db_column='lager_einheit_multiplizierer', decimal_places=4, max_digits=10)),
                ('base_unit', models.ForeignKey(blank=True, db_column='lager_einheit_basis', null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.warehouseunit')),
                ('period', models.ForeignKey(db_column='lager_einheit_periode', on_delete=django.db.models.deletion.CASCADE, to='core.period')),
            ],
            options={
                'db_table': 'lager_einheiten',
                'unique_together': {('source_id', 'period')},
            },
        ),
        migrations.CreateModel(
            name='WarehouseArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(db_column='lager_artikel_lagerartikel')),
                ('supplier_source_id', models.IntegerField(db_column='lager_artikel_lieferant')),
                ('supplier_article_number', models.CharField(blank=True, db_column='lager_artikel_lieferant_artikel', max_length=20, null=True)),
                ('priority', models.IntegerField(db_column='lager_artikel_prioritaet')),
                ('warehouse', models.IntegerField(blank=True, db_column='lager_artikel_lager', null=True)),
                ('flags', models.IntegerField(db_column='lager_artikel_flags')),
                ('max_stock', models.DecimalField(db_column='lager_artikel_maxStand', decimal_places=3, max_digits=10)),
                ('min_stock', models.DecimalField(db_column='lager_artikel_minStand', decimal_places=3, max_digits=10)),
                ('article', models.ForeignKey(db_column='lager_artikel_artikel', on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_entries', to='articles.article')),
                ('period', models.ForeignKey(blank=True, db_column='lager_artikel_periode', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.period')),
                ('unit', models.ForeignKey(blank=True, db_column='lager_artikel_einheit', null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.warehouseunit')),
            ],
            options={
                'db_table': 'lager_artikel',
                'unique_together': {('source_id', 'period')},
            },
        ),
    ]
