# Generated by Django 5.2 on 2026-03-25 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_remove_workplace_default_shift_duration'),
        ('pos_import', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(db_column='ist_anzahl', decimal_places=3, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(db_column='ist_artikel_id', on_delete=django.db.models.deletion.CASCADE, related_name='initial_inventories', to='pos_import.article')),
                ('period', models.ForeignKey(db_column='ist_periode_id', on_delete=django.db.models.deletion.CASCADE, related_name='initial_inventories', to='core.period')),
                ('workplace', models.ForeignKey(db_column='ist_arp_id', on_delete=django.db.models.deletion.CASCADE, to='core.workplace')),
            ],
            options={
                'db_table': 'initialer_stand',
                'unique_together': {('article', 'workplace', 'period')},
            },
        ),
        migrations.CreateModel(
            name='PeriodStartStockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(db_column='anzahl', decimal_places=3, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(db_column='artikel_id', on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='pos_import.article')),
                ('period', models.ForeignKey(blank=True, db_column='periode_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='core.period')),
            ],
            options={
                'db_table': 'periode_start_lagerstand',
                'unique_together': {('article', 'period')},
            },
        ),
        migrations.CreateModel(
            name='PhysicalCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_column='gst_datum')),
                ('quantity', models.DecimalField(db_column='gst_anzahl', decimal_places=3, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(db_column='gst_artikel_id', on_delete=django.db.models.deletion.CASCADE, related_name='physical_counts', to='pos_import.article')),
                ('period', models.ForeignKey(blank=True, db_column='gst_periode_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physical_counts', to='core.period')),
            ],
            options={
                'db_table': 'gezaehlter_stand',
                'indexes': [models.Index(fields=['date'], name='gezaehlter_stand_datum_idx')],
            },
        ),
    ]
