# Generated by Django 5.2 on 2026-03-30 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodstartstocklevel',
            name='period',
            field=models.ForeignKey(db_column='periode_id', on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='core.period'),
        ),
        migrations.AlterField(
            model_name='physicalcount',
            name='period',
            field=models.ForeignKey(db_column='gst_periode_id', on_delete=django.db.models.deletion.CASCADE, related_name='physical_counts', to='core.period'),
        ),
    ]
