# Generated by Django 5.2 on 2026-04-04 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_workplace_to_location"),
        ("inventory", "0003_rename_workplace_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="initialinventory",
            name="location",
            field=models.ForeignKey(
                db_column="ist_arp_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.location",
            ),
        ),
    ]
