# Generated by Django 5.2 on 2026-03-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='periode_bezeichnung', max_length=255)),
                ('checkpoint_year', models.IntegerField(blank=True, db_column='periode_checkpoint_jahr', null=True)),
                ('start', models.DateTimeField(db_column='periode_start')),
                ('end', models.DateTimeField(db_column='periode_ende')),
            ],
            options={
                'db_table': 'perioden',
                'ordering': ['-start'],
            },
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='arp_bezeichnung', max_length=255)),
            ],
            options={
                'db_table': 'arbeitsplaetze',
                'ordering': ['name'],
            },
        ),
    ]
