# Generated by Django 5.0.6 on 2026-03-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='periode_bezeichnung', max_length=255)),
                ('checkpoint_year', models.IntegerField(blank=True, db_column='periode_checkpoint_jahr', null=True)),
                ('start', models.DateTimeField(db_column='periode_start')),
                ('end', models.DateTimeField(db_column='periode_ende')),
            ],
            options={
                'db_table': 'perioden',
                'ordering': ['-start'],
            },
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='arp_bezeichnung', max_length=255)),
                ('default_shift_duration', models.FloatField(db_column='arp_std_dienst_dauer')),
            ],
            options={
                'db_table': 'arbeitsplaetze',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_column='cfg_key', max_length=255)),
                ('value_int', models.IntegerField(blank=True, db_column='cfg_valueI', null=True)),
                ('value_float', models.FloatField(blank=True, db_column='cfg_valueF', null=True)),
                ('value_str', models.TextField(blank=True, db_column='cfg_valueS', null=True)),
                ('valid_till', models.DateTimeField(db_column='cfg_validTill')),
            ],
            options={
                'db_table': 'config',
                'unique_together': {('key', 'valid_till')},
            },
        ),
    ]
