# Generated by Django 5.2 on 2026-03-24 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workplace',
            name='default_shift_duration',
        ),
    ]
