# Generated by Django 5.2 on 2026-04-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_period_options_userpreferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_reports', 'Can view reports'), ('run_import', 'Can run POS data import')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['-start']},
        ),
    ]
