# Generated by Django 5.2 on 2026-04-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='auto', max_length=10),
        ),
    ]
