# Generated by Django 5.2 on 2026-06-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userpreferences_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wz_source_id', models.IntegerField(blank=True, help_text='adresse_id from adressen_basis in Wiffzack; null for locally-created addresses.', null=True, unique=True)),
                ('anrede', models.CharField(blank=True, max_length=255, null=True)),
                ('vorname', models.CharField(blank=True, max_length=50, null=True)),
                ('nachname', models.CharField(blank=True, max_length=50, null=True)),
                ('firma', models.TextField(blank=True, null=True)),
                ('abteilung', models.TextField(blank=True, null=True)),
                ('strasse', models.CharField(blank=True, max_length=100, null=True)),
                ('plz', models.CharField(blank=True, max_length=10, null=True)),
                ('ort', models.CharField(blank=True, max_length=50, null=True)),
                ('telefon', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('uid', models.TextField(blank=True, null=True, verbose_name='UID-Nummer')),
                ('anmerkung', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adressen',
                'ordering': ['nachname', 'vorname', 'firma'],
            },
        ),
    ]
