# Generated by Django 5.2 on 2026-09-16 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Kunden-Nummernfolge',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wz_source_id', models.IntegerField(blank=True, help_text='adresse_id of the Wiffzack address this customer was created for; null for locally-created customers.', null=True, unique=True)),
                ('customer_number', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='Kundennummer')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('telefon', models.CharField(blank=True, max_length=50)),
                ('uid', models.CharField(blank=True, max_length=50, verbose_name='UID-Nummer')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.address', verbose_name='Standardadresse')),
            ],
            options={
                'verbose_name': 'Kunde',
                'verbose_name_plural': 'Kunden',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='core.customer', verbose_name='Kunde'),
        ),
    ]
