# Generated by Django 5.2 on 2026-04-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffConsumptionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption_date', models.DateTimeField()),
                ('department_name', models.CharField(max_length=255)),
                ('article_id', models.CharField(max_length=100)),
                ('article_name', models.CharField(max_length=200)),
                ('count', models.PositiveIntegerField()),
                ('year_month', models.CharField(max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'staff_consumption_entries',
                'ordering': ['-consumption_date'],
                'unique_together': {('consumption_date', 'department_name', 'article_id')},
            },
        ),
    ]
