# Generated by Django 5.2 on 2026-04-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockCountEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_date', models.DateTimeField()),
                ('article_id', models.CharField(max_length=100)),
                ('article_name', models.CharField(max_length=200)),
                ('location_id', models.IntegerField()),
                ('location_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('period_id_value', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stock_count_entries',
                'unique_together': {('article_id', 'location_id', 'count_date', 'period_id_value')},
            },
        ),
    ]
