# Generated by Django 5.2 on 2026-04-06 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_count', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockcountentry',
            unique_together={('article_id', 'location_id', 'count_date')},
        ),
        migrations.RemoveField(
            model_name='stockcountentry',
            name='period_id_value',
        ),
    ]
