# Generated by Django 5.2 on 2026-04-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_count', '0002_remove_period_id_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcountentry',
            name='package_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockcountentry',
            name='unit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
