# Generated by Django 5.2 on 2026-04-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_count', '0004_backfill_unit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcountentry',
            name='units_per_package',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockcountentry',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
