# Generated by Django 5.2 on 2026-04-08 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_count', '0006_backfill_units_per_package'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockcountentry',
            options={'ordering': ['-count_date']},
        ),
    ]
